
import java.awt.Graphics;
import static java.lang.System.in;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pivanovs3
 */
public class PapardeTriangle extends javax.swing.JFrame {

    /**
     * Creates new form PapardeTriangle
     */
    public PapardeTriangle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double[][] m1 = {{0, 0}, {0, 0.16}};
    double[][] m2 = {{0.85, 0.04}, {-0.04, 0.85}};
    double[][] m3 = {{0.2, -0.26}, {0.23, 0.22}};
    double[][] m4 = {{-0.15, 0.28}, {0.26, 0.24}};

    class PointD {

        double x, y;

        public PointD(double x, double y) {
            this.x = x;
            this.y = y;
        }
    }

    private PointD[] reizina(PointD[] ap, double[][] m) {
        for (int i = 0; i < 3; i++) {
            double x = ap[i].x;
            double y = ap[i].y;
            ap[i].x = (m[0][0] * x + m[0][1] * y);
            ap[i].y = (m[1][0] * x + m[1][1] * y);
        }

        return ap;
    }

    private PointD[] pieskaita(PointD[] p, int m) {
        for (int i = 0; i < 3; i++) {
            switch (m) {
                case 1:
                    p[i].y += 1.6;
                    break;
                case 2:
                    p[i].y += 1.6;
                    break;
                case 3:
                    p[i].y += 0.44;
                    break;
                default:
                    break;
            }
        }
        return p;
    }

    Graphics g = this.getGraphics();
    PointD[] ap = new PointD[3];
    
    private void draw() {
        Graphics g = this.getGraphics();
        PointD p = new PointD(10, 10);
        ap[0] = new PointD(10, 10);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PapardeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PapardeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PapardeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PapardeTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PapardeTriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
