
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.MemoryImageSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author pivanovs3
 */
public class Projiceeshana extends javax.swing.JFrame {

    /**
     * Creates new form Projiceeshana
     */
    public Projiceeshana() {
        initComponents();
    }

    double[][] punkti3D;
    double[][] projMat = {{1, 0}, {0, 1}, {Math.cos(Math.PI / 180 * 45), Math.sin(Math.PI / 180 * 45)}};
    double[][] punkti2D;
    Image img = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("zīmē");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("leņķis");

        jTextField2.setText("0");

        jButton2.setText("pagriezt X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Y");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Z");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");

        jTextField3.setText("0");

        jTextField4.setText("0");

        jButton5.setText("stretch");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(0, 296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(img, 100, 100, this);
    }

    private void init3d() {
        //int solis = Integer.parseInt(jTextField1.getText());
        //punkti3D = new double[(360 / solis + 1) * (240 / solis + 1)][3];
        punkti3D = new double[361*241][3];
        int i = 0;
        for (int x = -180; x <= 180; x += 1) {
            for (int z = -120; z <= 120; z += 1, i++) {
                punkti3D[i][0] = x;
                punkti3D[i][2] = z;
                punkti3D[i][1] = 40 * Math.sin(0.043 * Math.sqrt(x * x + z * z));
            }
        }
    }

    private void reizina() {
        //int solis = Integer.parseInt(jTextField1.getText());
        //punkti2D = new double[(360 / solis + 1) * (240 / solis + 1)][3];
        punkti2D = new double[361*241][2];
        for (int i = 0; i < 361*241; i++) {
            for (int k = 0; k < 2; k++) {
                punkti2D[i][k] = 0;
                for (int t = 0; t < 3; t++) {
                    punkti2D[i][k] = punkti2D[i][k] + punkti3D[i][t] * projMat[t][k];
                }
            }
        }
    }
    
    private void reizinaPg(double[][] matrix) {
        double tmp[][] = new double[361*241][3];
        for (int i = 0; i < 361*241; i++) {
            for (int k = 0; k < 3; k++) {
                tmp[i][k] = 0;
                for (int t = 0; t < 3; t++) {
                    tmp[i][k] = tmp[i][k] + punkti3D[i][t] * matrix[t][k];
                }
            }
        }
        for (int i = 0; i < 361*241; i++) {
            for (int k = 0; k < 3; k++) {
                punkti3D[i][k] = tmp[i][k];
            }
        }
        attelo();
    }

    private void attelo() {
        reizina();
        int w = 700;
        int h = 700;
        int[] pixels = new int[w * h];
        for (int i = 0; i < w * h; i++) {
            pixels[i] = (255 << 24) | (255 << 8);
        }
        double maxX = Double.MIN_VALUE;
        double maxY = Double.MIN_VALUE;
        double minX = Double.MAX_VALUE;
        double minY = Double.MAX_VALUE;
        for (int j = 0; j < 361*241; j++) {
            double x = punkti2D[j][0];
            double y = punkti2D[j][1];
            if (x > maxX) maxX = x;
            else if (x < minX) minX = x;
            if (y > maxY) maxY = y;
            else if (y < minY) minY = y;        
        }
        double smallY[] = new double[700];
        double bigY[] = new double[700];
        for (int i = 0; i < 700; i++) {
            smallY[i] = Double.MAX_VALUE;
            bigY[i] = Double.MIN_VALUE;
        }    
        for (int i = 0; i < 361*241; i++) {
            int x = (int)(punkti2D[i][0]+300);
            int y = (int)(punkti2D[i][1]+200);
            if (y >= smallY[(int)x]) {
                if (y > bigY[(int)x]) {
                    bigY[(int)x] =  y;
                    int j = (int) (x + w*y);
                    pixels[j] = (255 << 24) | 255;
                }
            } else {
                smallY[(int)x] = y;
                int j = (int) (x + w*y);
                pixels[j] = (255 << 24) | 255;
            }
        }
        System.out.println(maxX + " " + minX + " " + maxY + " " + minY);
        img = createImage(new MemoryImageSource(w, h, pixels, 0, (w)));
        repaint();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        init3d();
        attelo();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //for (int i = 100; i < 100; i++) {
        double lenkis = Double.parseDouble(jTextField2.getText()) * Math.PI/180;
        double grX[][] = {{1, 0, 0}, 
                        {0, Math.cos(lenkis), Math.sin(lenkis)}, 
                        {0, -Math.sin(lenkis), Math.cos(lenkis)}};
        reizinaPg(grX);
        
        //}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double lenkis = Double.parseDouble(jTextField2.getText()) * Math.PI/180;
        double grY[][] = {{Math.cos(lenkis), 0, -Math.sin(lenkis)}, 
                        {0, 1, 0}, 
                        {Math.sin(lenkis), 0, Math.cos(lenkis)}};
        reizinaPg(grY);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        double lenkis = Double.parseDouble(jTextField2.getText()) * Math.PI/180;
        double grZ[][] = {{Math.cos(lenkis), Math.sin(lenkis), 0}, 
                        {-Math.sin(lenkis), Math.cos(lenkis), 0}, 
                        {0, 0, 1}};
        reizinaPg(grZ);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(jTextField1.getText());
        double b = Double.parseDouble(jTextField3.getText());
        double c = Double.parseDouble(jTextField4.getText());
        double stretch[][] = {{a, 0, 0},
                            {0, b, 0},
                            {0, 0, c}};
        reizinaPg(stretch);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projiceeshana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projiceeshana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projiceeshana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projiceeshana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projiceeshana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
