/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thegreatkoks;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/**
 *
 * @author pivanovs3
 */
public class Dizhkoks extends javax.swing.JFrame {

    /**
     * Creates new form Dizhkoks
     */
    public Dizhkoks() {
        initComponents();
    }
    
    Graphics g;
    double alfa = Math.PI / 3;
    Random rand = new Random();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("uzzīmē kādu skaistu koku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 249, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 277, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void makeItBranch(double xCentre, double yCentre, double radius, double phi) {
        if (radius > 2) {
            
            //g.setColor(new Color(rand.nextInt(255), rand.nextInt(255), rand.nextInt(255)));
            double x1 = xCentre + radius * Math.cos(phi - alfa / 2);
            double y1 = yCentre - radius * Math.sin(phi - alfa / 2);
            double x2 = xCentre + radius * Math.cos(phi + alfa / 2);
            double y2 = yCentre - radius * Math.sin(phi + alfa / 2);
            g.drawLine((int) xCentre, (int) yCentre, (int) x1, (int) y1);
            g.drawLine((int) xCentre, (int) yCentre, (int) x2, (int) y2);
            radius *= 0.65;

            makeItBranch(x1, y1, radius, phi - alfa / 2);
            makeItBranch(x2, y2, radius, phi + alfa / 2);
            
        } else {
            g.setColor(Color.GREEN);
            
            //some code here
            double x1 = xCentre + radius * Math.cos(phi - alfa / 2);
            double x2 = xCentre + radius * Math.cos(phi + alfa / 2);
            double y1 = yCentre - radius * Math.sin(phi - alfa / 2);
            double y2 = yCentre - radius * Math.sin(phi + alfa / 2);
            g.drawLine((int) xCentre, (int) yCentre, (int) x1, (int) y1);
            g.drawLine((int) xCentre, (int) yCentre, (int) x2, (int) y2);
            
            g.setColor(Color.CYAN);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        g = this.getGraphics();
        g.setColor(Color.CYAN);
        g.drawLine(this.getWidth() / 2, this.getHeight(), this.getWidth() / 2, this.getHeight() / 5 * 4);
        makeItBranch(this.getWidth() / 2, this.getHeight() / 5 * 4, this.getHeight() / 4, Math.PI / 2);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dizhkoks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dizhkoks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dizhkoks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dizhkoks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dizhkoks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
